-- Blog posts tablosuna örnek veriler ekleme
INSERT INTO "public"."blog_posts" ("id", "title", "content", "excerpt", "image_url", "category", "published", "created_at", "updated_at") VALUES 
('b1', 'Dijital Pazarlamada Yapay Zeka Trendleri', 'Yapay zeka teknolojilerinin dijital pazarlama dünyasında nasıl kullanıldığını keşfedin. 2024 yılında öne çıkan AI trendleri ve uygulama alanları hakkında detaylı bir analiz sunuyoruz. Makine öğrenmesi, doğal dil işleme ve tahminsel analitik gibi teknolojilerin pazarlama stratejilerinizi nasıl dönüştürebileceğini öğrenin.', '2024 yılında dijital pazarlamada yapay zeka kullanımı ve trendleri hakkında detaylı bir analiz.', 'https://images.pexels.com/photos/4126684/pexels-photo-4126684.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'AI', true, '2024-01-15 10:00:00+00', '2024-01-15 10:00:00+00'),

('b2', 'SEO Optimizasyonu İpuçları', 'Web sitenizi arama motorlarında üst sıralara taşıyacak pratik SEO ipuçları. Teknik SEO, içerik optimizasyonu, link building ve yerel SEO stratejilerini kapsamlı bir şekilde ele alıyoruz. Google algoritma güncellemelerini takip ederek güncel SEO tekniklerini uygulayın.', 'Etkili SEO stratejileri ve web sitenizi optimize etme yöntemleri.', 'https://images.pexels.com/photos/6177662/pexels-photo-6177662.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'SEO', true, '2024-01-10 14:30:00+00', '2024-01-10 14:30:00+00'),

('b3', 'Sosyal Medya Pazarlama Stratejileri', 'Sosyal medya platformlarında markanızı nasıl etkili bir şekilde tanıtacağınızı öğrenin. Instagram, Facebook, LinkedIn ve TikTok için özel stratejiler geliştirin. İçerik planlama, topluluk yönetimi ve influencer marketing konularında uzman tavsiyeleri alın.', 'Sosyal medya pazarlama stratejileri ve içerik planlama teknikleri.', 'https://images.pexels.com/photos/6177545/pexels-photo-6177545.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Sosyal Medya', true, '2024-01-05 09:15:00+00', '2024-01-05 09:15:00+00'),

('b4', 'Google Ads Kampanyalarınızı Optimize Etme', 'Google Ads kampanyalarınızdan maksimum verim almanın yolları. Anahtar kelime araştırması, reklam metni optimizasyonu, hedefleme stratejileri ve bütçe yönetimi konularında pratik ipuçları. ROI\'nizi artırmak için kanıtlanmış teknikleri uygulayın.', 'Google Ads kampanyalarınızdan maksimum verim almanın yolları ve optimizasyon teknikleri.', 'https://images.pexels.com/photos/4126743/pexels-photo-4126743.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Google Ads', true, '2024-01-01 16:45:00+00', '2024-01-01 16:45:00+00'),

('b5', 'E-posta Pazarlama Trendleri', 'E-posta pazarlamasının dijital pazarlama stratejilerindeki önemli rolü ve 2024 yılında öne çıkan trendler. Kişiselleştirme, otomasyon ve yapay zeka entegrasyonu ile e-posta kampanyalarınızı optimize edin. A/B testi ve segmentasyon teknikleri ile açılma oranlarınızı artırın.', '2024 e-posta pazarlama trendleri ve kişiselleştirme teknikleri.', 'https://images.pexels.com/photos/4126724/pexels-photo-4126724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'E-posta Pazarlaması', true, '2023-12-28 11:20:00+00', '2023-12-28 11:20:00+00'),

('b6', 'Web Tasarım Trendleri 2024', 'Web tasarımında kullanıcı deneyimini ön planda tutan yeni trendler ve teknolojiler. Mobil-first tasarım, mikro etkileşimler, performans optimizasyonu ve erişilebilirlik standartları. Modern web siteleri için güncel tasarım prensiplerini keşfedin.', '2024 web tasarım trendleri ve kullanıcı deneyimi odaklı yaklaşımlar.', 'https://images.pexels.com/photos/4126714/pexels-photo-4126714.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Web Tasarım', true, '2023-12-25 13:10:00+00', '2023-12-25 13:10:00+00'); 